name: Checks
on: push

jobs:
  build_x64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: 'gradle'
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 7
          platform: x64
      - name: Set arch variable
        id: vars
        run: echo "::set-output name=os_arch::$(uname -m)"

      - name: Build platform specific lib
        run: ./gradlew buildCryptoCpp
      - name: Upload the shared lib
        uses: actions/upload-artifact@v2
        with:
          name: lib-${{ runner.os }}-${{ steps.vars.outputs.os_arch }}
          path: crypto/build/bindings/libcrypto_jni.*